/* C ABI for claude-switch (schemaVersion 1). Generated by hand to match c_abi.rs. */
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CsEngine CsEngine;

/* Error codes — see design §8.5 */
enum CsErrorCode {
  CS_OK = 0,
  CS_ACCOUNT_NOT_FOUND = 1,
  CS_VALIDATION_FAILED = 2,
  CS_CONFIG_ERROR = 3,
  CS_CREDENTIAL_ERROR = 4,
  CS_CREDENTIAL_WRITE_FAILED = 5,
  CS_CREDENTIAL_READ_FAILED = 6,
  CS_LOCK_TIMEOUT = 7,
  CS_CLAUDE_CODE_LOCK_TIMEOUT = 8,
  CS_SESSION_IN_USE = 9,
  CS_KEYCHAIN_UNAVAILABLE = 10,
  CS_NETWORK = 11,
  CS_TRANSFER_ERROR = 12,
  CS_MIGRATION_ERROR = 13,
  CS_SCHEMA_UNSUPPORTED = 14,
  CS_ALREADY_RUNNING = 15,
  CS_INTERNAL = 16,
  CS_NULL_POINTER = 17,
  CS_INVALID_METHOD = 18,
  CS_JSON_PARSE = 19
};

/* Create engine. root_utf8 NULL = real home; non-NULL = isolated fixture root. */
CsEngine *cs_engine_create(const char *root_utf8, int32_t *out_err);

void cs_engine_free(CsEngine *eng);

/* JSON-RPC style: method + params_json → result allocated with cs_string_free. */
int32_t cs_engine_call(
    CsEngine *eng,
    const char *method_utf8,
    const char *params_json_utf8,
    char **out_json_utf8);

void cs_string_free(char *s);

const char *cs_error_code_string(int32_t code);

#ifdef __cplusplus
}
#endif
